version: '3.8'

services:
  blackbox-arp-exporter:
    build: .
    command: ["blackbox-arp-exporter", "-interface", "wlo1", "-listen-address", ":9300"]
    network_mode: host
    cap_add: 
      - ALL